In [38]:
import pandas as pd

In [39]:
dataframe = pd.read_csv("../datasets/final_df.csv")

In [40]:
def define_gravity(df,name,treshold):
    df[name] = df["days_out"].apply(
        lambda x: int(x.split()[0]) >= treshold
    )
    return df

In [41]:
dataframe = define_gravity(dataframe,"gravity_injury_90",90)

In [42]:
dataframe.head()

,Unnamed: 0,Unnamed: 0_x,player,season_x,injury,from,until,days_out,missed_matches,last_season,...,physic,movement_acceleration,movement_sprint_speed,movement_reactions,movement_balance,power_stamina,power_strength,season,matched_short_name,gravity_injury_90
0,0,0,Manuel Neuer,24/25,Torn muscle fiber,"Mar 6, 2025","Apr 30, 2025",56 days,10,23/24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1,1,Manuel Neuer,24/25,Rib fracture,"Dec 6, 2024","Dec 31, 2024",26 days,4,23/24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,2,2,Manuel Neuer,24/25,Thigh problems,"Sep 18, 2024","Sep 26, 2024",9 days,1,23/24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,3,3,Manuel Neuer,23/24,infection,"May 27, 2024","May 31, 2024",5 days,-,22/23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,4,4,Manuel Neuer,23/24,Torn muscle fiber,"Mar 20, 2024","Apr 8, 2024",20 days,4,22/23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [43]:
dataframe.drop(columns=["Unnamed: 0","Unnamed: 0_x"],inplace=True)

Este preprocesado consiste en agrupar el dataframe a nivel temporada, es decir para cada jugador y temporada me vas a decir si durante esa temporada sufrio alguna lesion

In [44]:
grouped_df_90 = dataframe.groupby(['player', 'season_x'])['gravity_injury_90'].any().reset_index()

grouped_df_90.rename(columns={
    'season_x': 'season',
    'gravity_injury_90': 'had_major_injury_90'
}, inplace=True)

In [45]:
dataframe_aux = dataframe.drop(columns=["injury","from","until","days_out","missed_matches","gravity_injury_90"]).drop_duplicates()

In [46]:
dataframe_aux.head()

,player,season_x,last_season,season_y,nation,pos,age,born,MP,Starts,...,defending,physic,movement_acceleration,movement_sprint_speed,movement_reactions,movement_balance,power_stamina,power_strength,season,matched_short_name
0,Manuel Neuer,24/25,23/24,23/24,GER,GK,37.0,1986.0,23.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Manuel Neuer,23/24,22/23,22/23,GER,GK,36.0,1986.0,12.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Manuel Neuer,22/23,21/22,21/22,GER,GK,35.0,1986.0,28.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Manuel Neuer,21/22,20/21,20/21,GER,GK,34.0,1986.0,33.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Manuel Neuer,18/19,17/18,17/18,GER,GK,31.0,1986.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
dataframe_study = pd.merge(grouped_df_90,dataframe_aux,how = "left",left_on=['player', 'season'],right_on = ["player","season_x"],suffixes=("_1","_2"))

In [48]:
dataframe_study

,player,season_1,had_major_injury_90,season_x,last_season,season_y,nation,pos,age,born,...,defending,physic,movement_acceleration,movement_sprint_speed,movement_reactions,movement_balance,power_stamina,power_strength,season_2,matched_short_name
0,Aaron Cresswell,18/19,False,18/19,17/18,17/18,ENG,DF,27.0,1989.0,...,73.0,68.0,75.0,76.0,68.0,90.0,82.0,59.0,18/19,Aaron Cresswell
1,Aaron Cresswell,19/20,False,19/20,18/19,18/19,ENG,DF,28.0,1989.0,...,74.0,69.0,74.0,72.0,73.0,85.0,74.0,62.0,19/20,Aaron Cresswell
2,Aaron Cresswell,20/21,False,20/21,19/20,19/20,ENG,DF,29.0,1989.0,...,74.0,67.0,74.0,69.0,73.0,83.0,71.0,61.0,20/21,Aaron Cresswell
3,Aaron Cresswell,24/25,False,24/25,23/24,23/24,ENG,"DF,FW",33.0,1989.0,...,77.0,67.0,66.0,51.0,78.0,75.0,73.0,61.0,24/25,Aaron Cresswell
4,Aaron Mooy,18/19,False,18/19,17/18,17/18,AUS,MF,26.0,1990.0,...,66.0,76.0,67.0,70.0,69.0,73.0,78.0,76.0,18/19,Aaron Mooy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6327,È˜tefan Radu,18/19,False,18/19,17/18,17/18,ROU,DF,30.0,1986.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6328,È˜tefan Radu,19/20,False,19/20,18/19,18/19,ROU,DF,31.0,1986.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6329,È˜tefan Radu,20/21,False,20/21,19/20,19/20,ROU,DF,32.0,1986.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6330,È˜tefan Radu,21/22,False,21/22,20/21,20/21,ROU,DF,33.0,1986.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6331,È˜tefan Radu,22/23,False,22/23,21/22,21/22,ROU,DF,34.0,1986.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
dataframe_study.to_csv("datasetAgrupado90.csv")

In [50]:
dataframe_study.dtypes

player                  object
season_1                object
had_major_injury_90       bool
season_x                object
last_season             object
                        ...
movement_balance       float64
power_stamina          float64
power_strength         float64
season_2                object
matched_short_name      object
Length: 62, dtype: object

In [51]:
dataframe_study=pd.read_csv("datasetAgrupado90.csv")

In [52]:
dataframe_study

,Unnamed: 0,player,season_1,had_major_injury_90,season_x,last_season,season_y,nation,pos,age,...,defending,physic,movement_acceleration,movement_sprint_speed,movement_reactions,movement_balance,power_stamina,power_strength,season_2,matched_short_name
0,0,Aaron Cresswell,18/19,False,18/19,17/18,17/18,ENG,DF,27.0,...,73.0,68.0,75.0,76.0,68.0,90.0,82.0,59.0,18/19,Aaron Cresswell
1,1,Aaron Cresswell,19/20,False,19/20,18/19,18/19,ENG,DF,28.0,...,74.0,69.0,74.0,72.0,73.0,85.0,74.0,62.0,19/20,Aaron Cresswell
2,2,Aaron Cresswell,20/21,False,20/21,19/20,19/20,ENG,DF,29.0,...,74.0,67.0,74.0,69.0,73.0,83.0,71.0,61.0,20/21,Aaron Cresswell
3,3,Aaron Cresswell,24/25,False,24/25,23/24,23/24,ENG,"DF,FW",33.0,...,77.0,67.0,66.0,51.0,78.0,75.0,73.0,61.0,24/25,Aaron Cresswell
4,4,Aaron Mooy,18/19,False,18/19,17/18,17/18,AUS,MF,26.0,...,66.0,76.0,67.0,70.0,69.0,73.0,78.0,76.0,18/19,Aaron Mooy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6327,6327,È˜tefan Radu,18/19,False,18/19,17/18,17/18,ROU,DF,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6328,6328,È˜tefan Radu,19/20,False,19/20,18/19,18/19,ROU,DF,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6329,6329,È˜tefan Radu,20/21,False,20/21,19/20,19/20,ROU,DF,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6330,6330,È˜tefan Radu,21/22,False,21/22,20/21,20/21,ROU,DF,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6331,6331,È˜tefan Radu,22/23,False,22/23,21/22,21/22,ROU,DF,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
dataframe_study.drop(columns=["season_x","last_season","season_y",'_merge','short_name','long_name',
                              'player_positions','season_2','matched_short_name'],inplace=True)

In [54]:
cat_cols = dataframe_study.select_dtypes(include=['object', 'category', 'string']).columns.tolist()

In [55]:
cat_cols

['player', 'season_1', 'nation', 'pos', 'work_rate', 'body_type']

In [56]:
len(set(dataframe_study["body_type"]))

11

#### Tratamiento variables categoricas
Hay muchos jugadores para considerar hacer oneHotEncoding, algo similar pasa con los paises, por lo que se hara Ordinal Encoding para estos, como si fuese un ID para el nombre del jugador, por otro lado, la nacion y la temporada tambiÃ©n seran numeros ordinales. Por Ãºltimo work_rate, pos y body_type utilizarÃ¡n one Hot encoding

In [34]:
dataframe_study.head()

,Unnamed: 0,player,season_1,had_major_injury_90,nation,pos,age,born,MP,Starts,...,passing,dribbling,defending,physic,movement_acceleration,movement_sprint_speed,movement_reactions,movement_balance,power_stamina,power_strength
0,0,Aaron Cresswell,18/19,False,ENG,DF,27.0,1989.0,36.0,35.0,...,72.0,76.0,73.0,68.0,75,76,68,90,82,59
1,1,Aaron Cresswell,19/20,False,ENG,DF,28.0,1989.0,20.0,18.0,...,74.0,76.0,74.0,69.0,74,72,73,85,74,62
2,2,Aaron Cresswell,24/25,False,ENG,"DF,FW",33.0,1989.0,11.0,4.0,...,75.0,75.0,77.0,67.0,66,51,78,75,73,61
3,3,Aaron Mooy,18/19,False,AUS,MF,26.0,1990.0,36.0,34.0,...,77.0,74.0,66.0,76.0,67,70,69,73,78,76
4,4,Aaron Mooy,19/20,False,AUS,"MF,FW",27.0,1990.0,29.0,25.0,...,79.0,75.0,70.0,75.0,64,62,74,74,77,74

In [35]:
dataframe_study.drop(columns=["Unnamed: 0"],inplace=True)

In [37]:
dataframe_study.to_csv("datasetAgrupado90.csv")