In [2]:
import pandas as pd
import soccerdata as sd

[07/21/25 21:59:07] INFO     No custom team name replacements found. You can configure these in       ]8;id=291225;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=796913;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_config.py#91\91]8;;\
                             /Users/luisarizalopez/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=341249;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=739674;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_config.py#197\197]8;;\
                             /Users/luisarizalopez/soccerdata/config/league_dict.json.

In [3]:
dataframe_total = pd.read_csv("datasets/players_injuries.csv")

In [ ]:
jugadores = set(dataframe_total["name"])

In [5]:
fbref_big5 = sd.FBref(leagues='Big 5 European Leagues Combined', seasons=[17,18,19,20,21,22,23,24])

[07/21/25 22:00:40] INFO     Saving cached data to /Users/luisarizalopez/soccerdata/data/FBref       ]8;id=419235;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=951641;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site-packages/soccerdata/_common.py#263\263]8;;\

In [6]:
df_players_top5 = fbref_big5.read_player_season_stats(stat_type='standard')

[07/21/25 22:00:41] WARNING  /Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/site ]8;id=382932;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=957740;file:///Users/luisarizalopez/opt/anaconda3/envs/master_ML/lib/python3.10/warnings.py#109\109]8;;\
                             -packages/soccerdata/fbref.py:165: FutureWarning: The behavior of
                             DataFrame concatenation with empty or all-NA entries is deprecated. In
                             a future version, this will no longer exclude empty or all-NA columns
                             when determining the result dtypes. To retain the old behavior,
                             exclude the relevant entries before the concat operation.
                               pd.concat(dfs)

In [7]:
df_players_top5

                                                          nation    pos age  \

league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey               WAL     MF  26
                                  Ainsley Maitland-Niles     ENG  DF,MF  19
                                  Alex Iwobi                 NGA  MF,FW  21
                                  Alex Oxlade-Chamberlain    ENG     DF  23
                                  Alexandre Lacazette        FRA     FW  26
...                                                          ...    ...  ..
ITA-Serie A        2425   Venezia Nicholas Pierini           ITA     MF  25
                                  Nunzio Lella               ITA     MF  24
                                  Richie Sagrado             BEL     DF  20
                                  Ridgeciano Haps            SUR     DF  31
                                  Saad El Haddad             MAR     MF  19

                                                           born Playing Time  \
                                                                          MP
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey             1990           24
                                  Ainsley Maitland-Niles   1997           15
                                  Alex Iwobi               1996           26
                                  Alex Oxlade-Chamberlain  1993            3
                                  Alexandre Lacazette      1991           32
...                                                         ...          ...
ITA-Serie A        2425   Venezia Nicholas Pierini         1998            2
                                  Nunzio Lella             2000            1
                                  Richie Sagrado           2004            3
                                  Ridgeciano Haps          1993           25
                                  Saad El Haddad           2005            3

                                                                              \
                                                          Starts   Min   90s
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey                21  1846  20.5
                                  Ainsley Maitland-Niles       8   914  10.2
                                  Alex Iwobi                  22  1830  20.3
                                  Alex Oxlade-Chamberlain      3   241   2.7
                                  Alexandre Lacazette         26  2202  24.5
...                                                          ...   ...   ...
ITA-Serie A        2425   Venezia Nicholas Pierini             0    83   0.9
                                  Nunzio Lella                 0     5   0.1
                                  Richie Sagrado               3   140   1.6
                                  Ridgeciano Haps             14  1369  15.2
                                  Saad El Haddad               0    30   0.3

                                                          Performance      \
                                                                  Gls Ast
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey                      7   8
                                  Ainsley Maitland-Niles            0   0
                                  Alex Iwobi                        3   5
                                  Alex Oxlade-Chamberlain           0   0
                                  Alexandre Lacazette              14   4
...                                                               ...  ..
ITA-Serie A        2425   Venezia Nicholas Pierini                  0   0
                                  Nunzio Lella                      0   0
                                  Richie Sagrado                    0   0
                                  Ridgeciano Haps                   1   1
                                  Saad El Haddad                    0   0

                                                           ... Per 90 Minutes  \
                                                           ...            Gls
league             season team    player                   ...
ENG-Premier League 1718   Arsenal Aaron Ramsey             ...           0.34
                                  Ainsley Maitland-Niles   ...            0.0
                                  Alex Iwobi               ...           0.15
                                  Alex Oxlade-Chamberlain  ...            0.0
                                  Alexandre Lacazette      ...           0.57
...                                                        ...            ...
ITA-Serie A        2425   Venezia Nicholas Pierini         ...            0.0
                                  Nunzio Lella             ...            0.0
                                  Richie Sagrado           ...            0.0
                                  Ridgeciano Haps          ...           0.07
                                  Saad El Haddad           ...            0.0

                                                                             \
                                                            Ast   G+A  G-PK
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey             0.39  0.73  0.34
                                  Ainsley Maitland-Niles    0.0   0.0   0.0
                                  Alex Iwobi               0.25  0.39  0.15
                                  Alex Oxlade-Chamberlain   0.0   0.0   0.0
                                  Alexandre Lacazette      0.16  0.74  0.49
...                                                         ...   ...   ...
ITA-Serie A        2425   Venezia Nicholas Pierini          0.0   0.0   0.0
                                  Nunzio Lella              0.0   0.0   0.0
                                  Richie Sagrado            0.0   0.0   0.0
                                  Ridgeciano Haps          0.07  0.13  0.07
                                  Saad El Haddad            0.0   0.0   0.0

                                                                              \
                                                          G+A-PK    xG   xAG
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey              0.73   0.3  0.26
                                  Ainsley Maitland-Niles     0.0  0.02  0.08
                                  Alex Iwobi                0.39  0.19  0.17
                                  Alex Oxlade-Chamberlain    0.0  0.09  0.19
                                  Alexandre Lacazette       0.65  0.56  0.18
...                                                          ...   ...   ...
ITA-Serie A        2425   Venezia Nicholas Pierini           0.0  0.04   0.1
                                  Nunzio Lella               0.0   0.0   0.0
                                  Richie Sagrado             0.0  0.03   0.0
                                  Ridgeciano Haps           0.13  0.08  0.05
                                  Saad El Haddad             0.0   0.0  0.07

                                                                        \
                                                          xG+xAG  npxG
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey              0.56   0.3
                                  Ainsley Maitland-Niles    0.11  0.02
                                  Alex Iwobi                0.36  0.19
                                  Alex Oxlade-Chamberlain   0.29  0.09
                                  Alexandre Lacazette       0.74  0.49
...                                                          ...   ...
ITA-Serie A        2425   Venezia Nicholas Pierini          0.13  0.04
                                  Nunzio Lella               0.0   0.0
                                  Richie Sagrado            0.03  0.03
                                  Ridgeciano Haps           0.13  0.08
                                  Saad El Haddad            0.07   0.0


                                                          npxG+xAG
league             season team    player
ENG-Premier League 1718   Arsenal Aaron Ramsey                0.56
                                  Ainsley Maitland-Niles      0.11
                                  Alex Iwobi                  0.36
                                  Alex Oxlade-Chamberlain     0.29
                                  Alexandre Lacazette         0.67
...                                                            ...
ITA-Serie A        2425   Venezia Nicholas Pierini            0.13
                                  Nunzio Lella                 0.0
                                  Richie Sagrado              0.03
                                  Ridgeciano Haps             0.13
                                  Saad El Haddad              0.07

[22418 rows x 33 columns]

In [8]:
df_players_top5.to_excel("excelFbref/fileFbref.xlsx", sheet_name='top5_pre')

In [9]:
fbref_info_post = pd.read_excel("excelFbref/fileFbref_post.xlsx")

In [10]:
fbref_info_post.head()

,season,player,nation,pos,age,born,MP,Starts,Min,90s,...,Gls90,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90
0,17/18,Aaron Ramsey,WAL,MF,26.0,1990.0,24,21,1846,20.5,...,0.34,0.39,0.73,0.34,0.73,0.30,0.26,0.56,0.30,0.56
1,17/18,Ainsley Maitland-Niles,ENG,"DF,MF",19.0,1997.0,15,8,914,10.2,...,0.00,0.00,0.00,0.00,0.00,0.02,0.08,0.11,0.02,0.11
2,17/18,Alex Iwobi,NGA,"MF,FW",21.0,1996.0,26,22,1830,20.3,...,0.15,0.25,0.39,0.15,0.39,0.19,0.17,0.36,0.19,0.36
3,17/18,Alex Oxlade-Chamberlain,ENG,DF,23.0,1993.0,3,3,241,2.7,...,0.00,0.00,0.00,0.00,0.00,0.09,0.19,0.29,0.09,0.29
4,17/18,Alexandre Lacazette,FRA,FW,26.0,1991.0,32,26,2202,24.5,...,0.57,0.16,0.74,0.49,0.65,0.56,0.18,0.74,0.49,0.67

In [11]:
dataframe_total.rename(columns={"name": "player"},inplace=True)
dataframe_total.head()

,player,season,injury,from,until,days_out,missed_matches,last_season
0,Manuel Neuer,24/25,Torn muscle fiber,"Mar 6, 2025","Apr 30, 2025",56 days,10,23/24
1,Manuel Neuer,24/25,Rib fracture,"Dec 6, 2024","Dec 31, 2024",26 days,4,23/24
2,Manuel Neuer,24/25,Thigh problems,"Sep 18, 2024","Sep 26, 2024",9 days,1,23/24
3,Manuel Neuer,23/24,infection,"May 27, 2024","May 31, 2024",5 days,-,22/23
4,Manuel Neuer,23/24,Torn muscle fiber,"Mar 20, 2024","Apr 8, 2024",20 days,4,22/23

In [12]:
df_merged = pd.merge(dataframe_total, fbref_info_post, how='left', left_on=['player', 'last_season'], right_on = ['player','season'],indicator=True)

In [13]:
df_merged_v2 = df_merged.dropna()

In [ ]:
df_merged_v2.to_csv("datasets/dataframe_preFifa.csv")

In [2]:
import pandas as pd
pd.read_csv("../datasets/dataframe_preFifa.csv").head()

,Unnamed: 0,player,season_x,injury,from,until,days_out,missed_matches,last_season,season_y,...,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90,_merge
0,0,Manuel Neuer,24/25,Torn muscle fiber,"Mar 6, 2025","Apr 30, 2025",56 days,10,23/24,23/24,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,both
1,1,Manuel Neuer,24/25,Rib fracture,"Dec 6, 2024","Dec 31, 2024",26 days,4,23/24,23/24,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,both
2,2,Manuel Neuer,24/25,Thigh problems,"Sep 18, 2024","Sep 26, 2024",9 days,1,23/24,23/24,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,both
3,3,Manuel Neuer,23/24,infection,"May 27, 2024","May 31, 2024",5 days,-,22/23,22/23,...,0.0,0.0,0.0,0.0,0.02,0.0,0.02,0.02,0.02,both
4,4,Manuel Neuer,23/24,Torn muscle fiber,"Mar 20, 2024","Apr 8, 2024",20 days,4,22/23,22/23,...,0.0,0.0,0.0,0.0,0.02,0.0,0.02,0.02,0.02,both

In [3]:
pd.read_csv("../datasets/dataframe_preFifa.csv").columns

Index(['Unnamed: 0', 'player', 'season_x', 'injury', 'from', 'until',
       'days_out', 'missed_matches', 'last_season', 'season_y', 'nation',
       'pos', 'age', 'born', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A',
       'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG',
       'PrgC', 'PrgP', 'PrgR', 'Gls90', 'Ast90', 'G+A90', 'G-PK90', 'G+A-PK90',
       'xG90', 'xAG90', 'xG+xAG90', 'npxG90', 'npxG+xAG90', '_merge'],
      dtype='object')